In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import rc

# 기본 글꼴을 NanumGothic으로 변경
rc("font", family="D2Coding ligature")

## sas to csv

In [3]:
pd_sas = pd.read_sas('dataset\hn22_all.sas7bdat', format='sas7bdat')
pd_sas.iloc[1:20]

,mod_d,ID,ID_fam,year,region,town_t,apt_t,psu,sex,age,...,N_RETIN,N_B1,N_B2,N_NIAC,N_FOLATE,N_VITC,LF_secur_y,LF_BUYER,LF_SAFE,N_DUSUAL
1,b'2024.01.11.',b'YA01220303',b'YA012203',2022.0,1.0,1.0,2.0,b'YA01',1.0,30.0,...,732.385000,1.829417,2.017004,18.342991,329.385371,79.903529,1.0,NaN,1.0,b'3'
2,b'2024.01.11.',b'YA01220304',b'YA012203',2022.0,1.0,1.0,2.0,b'YA01',2.0,25.0,...,0.000000,0.262020,1.379288,3.042505,69.694336,2.776080,1.0,1.0,1.0,b'2'
3,b'2024.01.11.',b'YA01236501',b'YA012365',2022.0,1.0,1.0,2.0,b'YA01',1.0,66.0,...,100.898983,1.338621,2.325439,18.325182,633.687278,112.775603,1.0,NaN,1.0,b'2'
4,b'2024.01.11.',b'YA01236502',b'YA012365',2022.0,1.0,1.0,2.0,b'YA01',2.0,62.0,...,128.641794,1.317710,2.564474,17.852091,690.090821,121.924030,1.0,1.0,1.0,b'2'
5,b'2024.01.11.',b'YA01238501',b'YA012385',2022.0,1.0,1.0,2.0,b'YA01',1.0,64.0,...,21.941000,1.089154,0.854851,6.100582,146.984927,7.582871,1.0,NaN,1.0,b'2'
6,b'2024.01.11.',b'YA01238502',b'YA012385',2022.0,1.0,1.0,2.0,b'YA01',2.0,61.0,...,13.821068,0.677016,0.768971,6.031566,128.975209,6.912674,1.0,1.0,1.0,b'2'
7,b'2024.01.11.',b'YA01238503',b'YA012385',2022.0,1.0,1.0,2.0,b'YA01',2.0,22.0,...,46.788987,0.979713,1.240742,12.247315,193.805268,21.886867,1.0,NaN,1.0,b'2'
8,b'2024.01.11.',b'YA01240601',b'YA012406',2022.0,1.0,1.0,2.0,b'YA01',2.0,53.0,...,34.502053,0.696156,0.855777,9.779649,291.662535,116.314127,1.0,1.0,1.0,b'1'
9,b'2024.01.11.',b'YA01240602',b'YA012406',2022.0,1.0,1.0,2.0,b'YA01',2.0,24.0,...,363.024587,1.221893,2.439917,14.440876,224.554183,46.079284,1.0,NaN,1.0,b'3'
10,b'2024.01.11.',b'YA01240604',b'YA012406',2022.0,1.0,1.0,2.0,b'YA01',2.0,79.0,...,44.043853,1.113441,0.995076,7.457263,246.493283,258.217201,1.0,NaN,1.0,b'2'
11,b'2024.01.11.',b'YA01248702',b'YA012487',2022.0,1.0,1.0,2.0,b'YA01',2.0,48.0,...,149.570011,1.265462,2.119161,10.708992,521.979859,189.570458,1.0,1.0,1.0,b'2'
12,b'2024.01.11.',b'YA01256702',b'YA012567',2022.0,1.0,1.0,2.0,b'YA01',2.0,50.0,...,66.780000,0.483740,0.941556,4.255963,446.652731,157.983265,1.0,1.0,1.0,b'2'
13,b'2024.01.11.',b'YA01305301',b'YA013053',2022.0,1.0,1.0,2.0,b'YA01',1.0,46.0,...,235.196064,2.908611,3.153613,21.677415,504.893890,172.330854,1.0,NaN,1.0,b'2'
14,b'2024.01.11.',b'YA01305302',b'YA013053',2022.0,1.0,1.0,2.0,b'YA01',2.0,40.0,...,329.625545,0.923368,1.759008,15.999435,344.942335,85.140696,1.0,1.0,1.0,b'2'
15,b'2024.01.11.',b'YA01307301',b'YA013073',2022.0,1.0,1.0,2.0,b'YA01',1.0,66.0,...,173.406572,3.096201,2.711872,27.635609,303.011780,45.160663,1.0,NaN,1.0,b'2'
16,b'2024.01.11.',b'YA01307302',b'YA013073',2022.0,1.0,1.0,2.0,b'YA01',2.0,64.0,...,2.051198,0.258415,0.395381,4.070900,88.371195,9.590193,1.0,1.0,1.0,b'2'
17,b'2024.01.11.',b'YA01321401',b'YA013214',2022.0,1.0,1.0,2.0,b'YA01',1.0,63.0,...,203.363413,0.654453,1.193207,6.265977,344.493414,78.980985,1.0,NaN,1.0,b'2'
18,b'2024.01.11.',b'YA01321402',b'YA013214',2022.0,1.0,1.0,2.0,b'YA01',2.0,60.0,...,498.606655,1.288094,1.749589,10.395396,246.175782,55.015057,1.0,1.0,1.0,b'3'
19,b'2024.01.11.',b'YA01329501',b'YA013295',2022.0,1.0,1.0,2.0,b'YA01',2.0,68.0,...,127.255299,1.147022,1.572682,17.960091,454.152755,79.560368,1.0,1.0,1.0,b'2'

In [4]:
pd_sas.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 6265 entries, 0 to 6264
Columns: 623 entries, mod_d to N_DUSUAL
dtypes: float64(594), object(29)
memory usage: 29.8+ MB

In [5]:
pd_sas.to_csv("dataset/dataset.csv")

PermissionError: [Errno 13] Permission denied: 'dataset/dataset.csv'

## Get independent variable

변경 목록, 목록에 없는 것은 제외된 변수
- AS1_ID -> ID
- AS1_Sex -> sex
- AS1_Age -> age
- AS1_MarryA -> marri_1
- AS1_JobB -> occp
- AS1_EduA -> edu
- AS1_Income -> incm5
- AS1_Drink -> BD1
- AS1_TotAlc(음주량) -> BD2_1
- AS1_SmokeA -> BS3_1
- AS1_HvSmAm(흡연량) -> BS3_2
- AS1_PhyAct(하루 일과 중 육체적 활동 시간 고도, 중도, 경도) -> pa_aerobic(유산소 신체활동 실천율, 결측값:461) 
- AS1_Health -> D_1_1
- 고혈압여부 -> DI1_pr
- 당뇨여부 -> DE1_pr
- BMI -> HE_BMI
- RC -> remnant cholesterol, 직접 만들기
- AI -> 동맥경화지수(Atherogenic Index) 직접 만들기

In [9]:
df = pd_sas[["ID", "sex", "age", "marri_1", "occp", "edu", "incm5", "BD1", "BD2_1", "BS3_1", "BS3_2", "pa_aerobic", "D_1_1", "DI1_pr", "DE1_pr", "HE_BMI"]]

In [10]:
df.head()

,ID,sex,age,marri_1,occp,edu,incm5,BD1,BD2_1,BS3_1,BS3_2,pa_aerobic,D_1_1,DI1_pr,DE1_pr,HE_BMI
0,b'YA01220302',2.0,56.0,1.0,7.0,3.0,4.0,2.0,8.0,8.0,888.0,0.0,3.0,1.0,8.0,26.507517
1,b'YA01220303',1.0,30.0,2.0,3.0,4.0,3.0,2.0,2.0,8.0,888.0,1.0,2.0,8.0,8.0,27.152029
2,b'YA01220304',2.0,25.0,2.0,7.0,4.0,4.0,2.0,1.0,8.0,888.0,1.0,2.0,8.0,8.0,21.308131
3,b'YA01236501',1.0,66.0,1.0,7.0,4.0,4.0,2.0,2.0,3.0,888.0,0.0,2.0,8.0,8.0,23.577207
4,b'YA01236502',2.0,62.0,1.0,6.0,3.0,3.0,2.0,1.0,8.0,888.0,1.0,2.0,8.0,8.0,21.839183

In [11]:
df_set_index = df.set_index('ID')

In [13]:
df_set_index.head()

,sex,age,marri_1,occp,edu,incm5,BD1,BD2_1,BS3_1,BS3_2,pa_aerobic,D_1_1,DI1_pr,DE1_pr,HE_BMI
ID,,,,,,,,,,,,,,,
b'YA01220302',2.0,56.0,1.0,7.0,3.0,4.0,2.0,8.0,8.0,888.0,0.0,3.0,1.0,8.0,26.507517
b'YA01220303',1.0,30.0,2.0,3.0,4.0,3.0,2.0,2.0,8.0,888.0,1.0,2.0,8.0,8.0,27.152029
b'YA01220304',2.0,25.0,2.0,7.0,4.0,4.0,2.0,1.0,8.0,888.0,1.0,2.0,8.0,8.0,21.308131
b'YA01236501',1.0,66.0,1.0,7.0,4.0,4.0,2.0,2.0,3.0,888.0,0.0,2.0,8.0,8.0,23.577207
b'YA01236502',2.0,62.0,1.0,6.0,3.0,3.0,2.0,1.0,8.0,888.0,1.0,2.0,8.0,8.0,21.839183

In [15]:
df_set_index.to_csv("dataset/res_basic.csv")